// <auto-generated />
using System;
using MedMonitor24_7.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedMonitor24_7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedMonitor24_7.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionID"));

                    b.Property<DateTime>("AdmitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BedID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("NurseID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AdmissionID");

                    b.HasIndex("BedID")
                        .IsUnique()
                        .HasFilter("[DischargeDate] IS NULL");

                    b.HasIndex("DoctorID");

                    b.HasIndex("NurseID");

                    b.HasIndex("PatientID")
                        .IsUnique()
                        .HasFilter("[DischargeDate] IS NULL");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.AdmissionVitalThreshold", b =>
                {
                    b.Property<int>("ThresholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThresholdID"));

                    b.Property<int>("AdmissionID")
                        .HasColumnType("int");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("VitalSignTypeID")
                        .HasColumnType("int");

                    b.HasKey("ThresholdID");

                    b.HasIndex("VitalSignTypeID");

                    b.HasIndex("AdmissionID", "VitalSignTypeID")
                        .IsUnique();

                    b.ToTable("AdmissionVitalThresholds");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Alert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<int>("AdmissionID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<int>("VitalSignTypeID")
                        .HasColumnType("int");

                    b.HasKey("AlertID");

                    b.HasIndex("VitalSignTypeID");

                    b.HasIndex("AdmissionID", "Status", "RaisedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.AlertAcknowledgement", b =>
                {
                    b.Property<int>("AckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AckID"));

                    b.Property<DateTime>("AckAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlertID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AckID");

                    b.HasIndex("AlertID");

                    b.HasIndex("UserID");

                    b.ToTable("AlertAcknowledgements");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Bed", b =>
                {
                    b.Property<int>("BedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedID"));

                    b.Property<string>("BedCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("BedID");

                    b.HasIndex("UnitID", "BedCode")
                        .IsUnique();

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<bool>("IsFromBot")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceiverUserID")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiverUserID");

                    b.HasIndex("SenderUserID", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ClinicalTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("AdmissionID")
                        .HasColumnType("int");

                    b.Property<int>("AssignedNurseID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reminder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepeatRule")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskID");

                    b.HasIndex("AdmissionID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("AssignedNurseID", "Status", "StartDateTime");

                    b.ToTable("ClinicalTasks");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<int>("BedID")
                        .HasColumnType("int");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DeviceID");

                    b.HasIndex("BedID");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.DeviceHeartbeat", b =>
                {
                    b.Property<int>("HeartbeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeartbeatID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<string>("Meta")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HeartbeatID");

                    b.HasIndex("DeviceID");

                    b.ToTable("DeviceHeartbeats");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.NotificationSettings", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartRateAlert")
                        .HasColumnType("bit");

                    b.Property<bool>("OxygenAlert")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskDelayAlert")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CompanionPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("PatientID");

                    b.HasIndex("Name");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.PatientReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("AdmissionID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("AdmissionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UploadedByUserID");

                    b.ToTable("PatientReports");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ReportCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportCategories");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ReportFile", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportFiles");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.SystemUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.TaskEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskEvents");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Unit", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<int>("MaxBeds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnitID");

                    b.HasIndex("Name");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.UserUnit", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.Property<string>("RoleInUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID", "UnitID");

                    b.HasIndex("UnitID");

                    b.ToTable("User_Unit");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.VitalSignReading", b =>
                {
                    b.Property<int>("ReadingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingID"));

                    b.Property<int>("AdmissionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<int>("VitalSignTypeID")
                        .HasColumnType("int");

                    b.HasKey("ReadingID");

                    b.HasIndex("VitalSignTypeID");

                    b.HasIndex("AdmissionID", "VitalSignTypeID", "ReadingTime");

                    b.ToTable("VitalSignReadings");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.VitalSignType", b =>
                {
                    b.Property<int>("VitalSignTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalSignTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("NormalMax")
                        .HasColumnType("real");

                    b.Property<float>("NormalMin")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VitalSignTypeID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VitalSignTypes");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Admission", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "Doctor")
                        .WithMany("DoctorAdmissions")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "Nurse")
                        .WithMany("NurseAdmissions")
                        .HasForeignKey("NurseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.AdmissionVitalThreshold", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Admission", "Admission")
                        .WithMany("VitalThresholds")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.VitalSignType", "VitalSignType")
                        .WithMany("AdmissionThresholds")
                        .HasForeignKey("VitalSignTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("VitalSignType");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Alert", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Admission", "Admission")
                        .WithMany("Alerts")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.VitalSignType", "VitalSignType")
                        .WithMany("Alerts")
                        .HasForeignKey("VitalSignTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("VitalSignType");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.AlertAcknowledgement", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Alert", "Alert")
                        .WithMany("Acknowledgements")
                        .HasForeignKey("AlertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "User")
                        .WithMany("AlertAcknowledgements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Bed", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Unit", "Unit")
                        .WithMany("Beds")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ChatMessage", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.SystemUser", "ReceiverUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ClinicalTask", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Admission", "Admission")
                        .WithMany("ClinicalTasks")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "AssignedNurse")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedNurseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("AssignedNurse");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Device", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Bed", "Bed")
                        .WithMany("Devices")
                        .HasForeignKey("BedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.DeviceHeartbeat", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Device", "Device")
                        .WithMany("Heartbeats")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.NotificationSettings", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.SystemUser", "User")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("MedMonitor24_7.Models.NotificationSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.PatientReport", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Admission", "Admission")
                        .WithMany("PatientReports")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.ReportCategory", "Category")
                        .WithMany("PatientReports")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "UploadedByUser")
                        .WithMany("UploadedReports")
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Category");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ReportFile", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.PatientReport", "Report")
                        .WithMany("Files")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.SystemUser", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.TaskEvent", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.ClinicalTask", "Task")
                        .WithMany("Events")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "User")
                        .WithMany("TaskEvents")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.UserUnit", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Unit", "Unit")
                        .WithMany("UserUnits")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.SystemUser", "User")
                        .WithMany("UserUnits")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.VitalSignReading", b =>
                {
                    b.HasOne("MedMonitor24_7.Models.Admission", "Admission")
                        .WithMany("VitalSignReadings")
                        .HasForeignKey("AdmissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedMonitor24_7.Models.VitalSignType", "VitalSignType")
                        .WithMany("VitalSignReadings")
                        .HasForeignKey("VitalSignTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("VitalSignType");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Admission", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ClinicalTasks");

                    b.Navigation("PatientReports");

                    b.Navigation("VitalSignReadings");

                    b.Navigation("VitalThresholds");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Alert", b =>
                {
                    b.Navigation("Acknowledgements");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Bed", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ClinicalTask", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Device", b =>
                {
                    b.Navigation("Heartbeats");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Patient", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.PatientReport", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.ReportCategory", b =>
                {
                    b.Navigation("PatientReports");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.SystemUser", b =>
                {
                    b.Navigation("AlertAcknowledgements");

                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("DoctorAdmissions");

                    b.Navigation("NotificationSettings");

                    b.Navigation("NurseAdmissions");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("TaskEvents");

                    b.Navigation("UploadedReports");

                    b.Navigation("UserUnits");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.Unit", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("UserUnits");
                });

            modelBuilder.Entity("MedMonitor24_7.Models.VitalSignType", b =>
                {
                    b.Navigation("AdmissionThresholds");

                    b.Navigation("Alerts");

                    b.Navigation("VitalSignReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
